[config]
default_to_workspace = false
skip_core_tasks = true

[env]
PROJ_NAME = "serde-encrypt"

[tasks.format]
script = ['''
#!/usr/bin/env bash -eux
cargo fmt --all
''']

[tasks.lint]
script = ['''
#!/usr/bin/env bash -eux
RUSTFLAGS='-D warnings' cargo clippy --all-targets --all-features
''']

[tasks.build]
script = ['''
#!/usr/bin/env bash -eux
RUSTFLAGS='-D warnings' cargo build --all-targets --all-features
''']

[tasks.test]
script = ['''
#!/usr/bin/env bash -eux
cargo test --all-targets --all-features
''']

[tasks.doc]
script = ['''
#!/usr/bin/env bash -eux
cargo clean --doc
cargo doc --no-deps --all-features
''']

[tasks.os-less-build]
script = ['''
#!/usr/bin/env bash -eux
rustup target add aarch64-unknown-none
RUSTFLAGS='-D warnings' cargo build --no-default-features --target=aarch64-unknown-none
''']

[tasks.lcov]
script = ['''
#!/usr/bin/env bash -eux
rm -rf target/debug/deps/${PROJ_NAME}-*
export CARGO_INCREMENTAL=0
export RUSTFLAGS="-Zprofile"

cargo +nightly build --verbose
cargo +nightly test --verbose

grcov ./target/debug/deps -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info
''']
