[package]
authors = ["Sho Nakatani <lay.sakura@gmail.com>"]
categories = ["no-std", "cryptography", "encoding"]
description = "Encrypts all the Serialize"
documentation = "https://docs.rs/serde-encrypt"
edition = "2018"
keywords = ["libsodium", "xsalsa20poly1305", "x25519", "serde", "serde-encrypt"] # up to 5 keywords, each keyword should have <= 20 chars
license = "MIT OR Apache-2.0"
name = "serde-encrypt"
readme = "../README.md"
repository = "https://github.com/laysakura/serde-encrypt"
version = "0.7.0"

[dependencies]
serde-encrypt-core = {version = "0.7.0", path = "../serde-encrypt-core", default-features = false}

bincode = {version = "1.3", optional = true}
postcard = {version = "1.0", default-features = false, features = ["alloc"]}
serde = {version = "1.0", default-features = false}
serde_cbor = {version = "0.11", default-features = false, features = ["alloc"]}

rand_chacha = {version = "0.3", default-features = false}
rand_core = {version = "0.6", default-features = false}

cfg-if = "1.0"

# Lazy static options
once_cell = {version = "1.8", optional = true}
spin = {version = "0.9.8", default-features = false, features = ["spin_mutex", "lazy"]}# default (available w/o std)

[dev-dependencies]
serde = {version = "1.0", default-features = false, features = ["derive", "alloc"]}# alloc for Vec, String
serde_json = {version = "1.0", default-features = false, features = ["alloc"]}
serde_repr = "0.1"

pretty_assertions = "1.0"

void = "1.0"

[features]
default = ["std"]
std = [
  "serde-encrypt-core/std",
  "serde/std",
  "bincode",
  "serde_cbor/std",
  "once_cell",
  "rand_chacha/std",
  "rand_core/getrandom", # from_entropy()
]
