//! X25519 key-pair (public-key and private-key).

use self::{
    private_key::{ReceiverPrivateKey, SenderPrivateKey},
    public_key::{ReceiverPublicKey, SenderPublicKey},
};

pub(in crate::key) mod private_key;
pub(in crate::key) mod public_key;

/// X25519 Key-pair generated by sender.
#[derive(Clone, Debug)]
pub struct SenderKeyPair {
    sender_private_key: SenderPrivateKey,
    sender_public_key: SenderPublicKey,
}

/// X25519 Key-pair generated by receiver.
#[derive(Clone, Debug)]
pub struct ReceiverKeyPair {
    receiver_private_key: ReceiverPrivateKey,
    receiver_public_key: ReceiverPublicKey,
}
